name: Terraform Infrastructure

on: 
  workflow_dispatch:
  push:
    paths:
      - 'infra/**'
    branches:
      - main

jobs:
  terraform_init_plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/environment/dev
    env:
      ARM_CLIENT_ID: ${{ fromJSON(secrets.creds).clientId }}
      ARM_CLIENT_SECRET: ${{ fromJSON(secrets.creds).clientSecret }}
      ARM_SUBSCRIPTION_ID: ${{ fromJSON(secrets.creds).subscriptionId }}
      ARM_TENANT_ID: ${{ fromJSON(secrets.creds).tenantId }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'workflow_dispatch'
        run: terraform apply -auto-approve
